### Get All Articles with Stored Token
GET http://127.0.0.1:8000/api/v1/articles/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQxNjcwNTMwfQ.TEXX_xuOUbTL_nR_tUDG1gwIg-022O5edjENf57uEuE


###
# Create a new user
POST http://127.0.0.1:8000/api/v1/users/signup/
Content-Type: application/json

{
    "username": "johndoe11",
    "email": "johndoe11@example.com",
    "password": "SecurePass123"
}

### Login and Save Token
POST http://127.0.0.1:8000/api/v1/users/login/
Content-Type: application/x-www-form-urlencoded

username=johndoe@example.com&password=SecurePass123
